-- ==============================================================================
-- DEPRECATED & DISABLED: DO NOT EXECUTE
-- This file previously granted public unauthenticated access (USING true) to all tables.
-- It has been decommissioned to enforce strict Row-Level Security (RLS) multi-tenancy.
-- 
-- Please use 'supabase/rls_policies.sql' for production-grade tenant isolation.
-- ==============================================================================
